/**
 * Default configuration
 *
 * You may copy and modify the code
 */
import type { Context, Meta } from '@content-collections/core';
import {
  compileMDX as baseCompileMDX,
  type Options as MDXOptions,
} from '@content-collections/mdx';
import {
  rehypeCode,
  remarkGfm,
  remarkHeading,
  remarkStructure,
  type RemarkHeadingOptions,
  type RehypeCodeOptions,
} from 'fumadocs-core/mdx-plugins';
import type { z as Zod } from 'zod';
import rehypeImgSize from 'rehype-img-size';
import {
  resolvePlugin,
  resolvePlugins,
  type ResolvePlugins,
} from '@/resolve-plugins';

export interface TransformOptions
  extends Omit<MDXOptions, 'remarkPlugins' | 'rehypePlugins'> {
  remarkPlugins?: ResolvePlugins;
  rehypePlugins?: ResolvePlugins;

  /**
   * Generate `structuredData`
   *
   * @defaultValue true
   */
  generateStructuredData?: boolean;

  remarkHeadingOptions?: RemarkHeadingOptions | boolean;
  rehypeCodeOptions?: RehypeCodeOptions | boolean;
}

export type SerializableTOC = {
  title: string;
  url: string;
  depth: number;
}[];

interface BaseDoc {
  _meta: Meta;
  content: string;
}

export async function transformMDX<D extends BaseDoc>(
  document: D,
  context: Context,
  options: TransformOptions = {},
): Promise<
  D & {
    body: string;
    toc: SerializableTOC;
    /**
     * `StructuredData` for search indexes
     */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Avoid wrong type errors
    structuredData: any;
  }
> {
  const {
    generateStructuredData = true,
    rehypeCodeOptions,
    remarkHeadingOptions,
    ...rest
  } = options;

  return context.cache(
    {
      type: 'fumadocs',
      document,
    },
    async () => {
      let data: Record<string, unknown> = {};

      const body = await baseCompileMDX(
        {
          ...context,
          // avoid nested caching
          cache: async (input, fn) => fn(input),
        },
        document,
        {
          cwd: process.cwd(),
          ...rest,
          rehypePlugins: resolvePlugins(
            (plugins) => [
              resolvePlugin(rehypeCode, rehypeCodeOptions ?? true),
              [rehypeImgSize, { dir: './public' }],
              ...plugins,
            ],
            rest.rehypePlugins,
          ),
          remarkPlugins: resolvePlugins(
            (plugins) => [
              remarkGfm,
              resolvePlugin(remarkHeading, remarkHeadingOptions ?? true),
              ...plugins,
              generateStructuredData && remarkStructure,
              () => {
                return (_, file) => {
                  data = file.data;
                };
              },
            ],
            rest.remarkPlugins,
          ),
        },
      );

      return {
        ...document,
        toc: data.toc as SerializableTOC,
        structuredData: data.structuredData,
        body,
      };
    },
  );
}

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type -- The type is dynamically generated by Zod
export function createDocSchema(z: typeof Zod) {
  return {
    title: z.string(),
    description: z.string().optional(),
    icon: z.string().optional(),
    full: z.boolean().optional(),
  };
}

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type -- The type is dynamically generated by Zod
export function createMetaSchema(z: typeof Zod) {
  return {
    title: z.string().optional(),
    pages: z.array(z.string()).optional(),
    icon: z.string().optional(),
    root: z.boolean().optional(),
    defaultOpen: z.boolean().optional(),
  };
}
