import { DocsLayout } from "next-docs-ui/layout";
import { tree } from "./tree";
import { Inter } from "next/font/google";
import { RootProvider } from "next-docs-ui/provider";
import type { Metadata } from "next";

import "next-docs-ui/style.css";
import "./style.css";

export const metadata: Metadata = {
    title: {
        default: "My App",
        template: "My App | %s",
    },
    description: "Generated by Next.js",
};

const inter = Inter({
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={inter.className}>
            <body
                style={{
                    position: "relative",
                    display: "flex",
                    flexDirection: "column",
                    minHeight: "100vh",
                }}
            >
                <RootProvider>
                    <div
                        style={{
                            position: "absolute",
                            inset: 0,
                            zIndex: -1,
                            overflow: "hidden",
                        }}
                    >
                        <div
                            style={{
                                position: "absolute",
                                top: 0,
                                right: 0,
                                width: "100%",
                                height: 500,
                                background:
                                    "linear-gradient(to bottom left, hsl(var(--gradient) / 0.5), hsl(var(--background)) 50%)",
                            }}
                        />
                        <div
                            style={{
                                position: "absolute",
                                bottom: 0,
                                left: 0,
                                width: "100%",
                                height: 500,
                                background:
                                    "linear-gradient(to top right, hsl(650 50% 50% / 0.2), transparent 30%)",
                            }}
                        />
                    </div>
                    <DocsLayout
                        tree={tree}
                        navTitle="My App"
                        githubUrl="https://github.com/SonMooSans/next-docs"
                    >
                        {children}
                    </DocsLayout>
                </RootProvider>
            </body>
        </html>
    );
}
