packages:
  - packages/*
  - apps/*
  - examples/*
  - '!examples/stackblitz'
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  msw: false
  protobufjs: false
  sharp: false
  vue-demi: false
