packages:
  - packages/*
  - apps/*
  - examples/*
  - '!examples/stackblitz'
minimumReleaseAgeExclude:
  - 'fuma-translate'
  - '@fuma-translate/*'
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  msw: false
  protobufjs: false
  sharp: false
  vue-demi: false
