import "./style.css";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="dark">
            <body>
                <nav className="sticky flex flex-row items-center top-0 left-0 right-0 h-12 bg-gradient-to-t from-background to-accent to-[150%] z-50">
                    <p className="text-sm text-muted-foreground mx-auto text-center">
                        next-docs
                    </p>
                </nav>
                {children}
            </body>
        </html>
    );
}
