// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/docs/*': {
    params: {
      '*': string;
    };
  };
  '/api/search': {
    params: {};
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/docs/*' | '/api/search';
  };
  'routes/home.tsx': {
    id: 'routes/home';
    page: '/';
  };
  'docs/page.tsx': {
    id: 'docs/page';
    page: '/docs/*';
  };
  'docs/search.ts': {
    id: 'docs/search';
    page: '/api/search';
  };
};

type RouteModules = {
  root: typeof import('./app/root.tsx');
  'routes/home': typeof import('./app/routes/home.tsx');
  'docs/page': typeof import('./app/docs/page.tsx');
  'docs/search': typeof import('./app/docs/search.ts');
};
