import path from 'node:path';
import type { Code } from 'mdast';
import { defineMdastPlugin } from 'satteri';
import {
  addNextRewrites,
  addReactRouterRoute,
  enableProcessedMarkdown,
  parseSourceFile,
  type SourceFile,
} from '@fumadocs/cli/codemod';
import {
  docsLlms,
  llmsRoutes,
  markdownRewrite,
  markdownUrl,
  tanstackMarkdownUrl,
  templates,
} from '@fumadocs/cli/features/llms';
import { mcpRoute, templates as mcpTemplates } from '@fumadocs/cli/features/mcp';
import { sourceRef } from '@fumadocs/cli/features/utils';
import { component as webmcp } from '@fumadocs/cli/features/webmcp';

declare module 'satteri' {
  interface DataMap {
    /** Markdown source edits read by `remark-llms` */
    _sourceEdits?: { start: number; end: number; text: string }[];
  }
}

const frameworks = ['next', 'react-router', 'tanstack-start', 'waku'] as const;

/** the docs show the setup of a Fumadocs MDX source */
const src = sourceRef(false);

/** apply a codemod to a stub file, with the inserted lines highlighted */
function codemod(name: string, code: string, edit: (file: SourceFile) => void) {
  const file = parseSourceFile(name, code);
  edit(file);
  const before = code.split('\n');
  const after = file.s.toString().split('\n');
  let start = 0;
  while (before[start] === after[start]) start++;
  let end = 0;
  while (before[before.length - 1 - end] === after[after.length - 1 - end]) end++;
  after[start] += ` // [!code ++:${after.length - start - end}]`;
  return after.join('\n');
}

/** the files written by CLI features, keyed by `<feature>/<framework>/<file>` */
function featureFiles() {
  const files: Record<string, string> = {
    'llms/docs-llms.ts': `import { llms } from 'fumadocs-core/source';\n${docsLlms(src)}\n`,
    'llms/source.config.ts': codemod(
      'source.config.ts',
      `import { defineDocs } from 'fumadocs-mdx/config';

export const docs = defineDocs({
  dir: 'content/docs',
});
`,
      enableProcessedMarkdown,
    ),
  };
  for (const framework of frameworks) {
    const base = `llms/${framework}`;
    const tanstack = framework === 'tanstack-start';
    files[`webmcp/${framework}/components/webmcp.tsx`] = webmcp({
      static: false,
      i18n: false,
      tanstack,
    });
    const mcp = mcpRoute(framework);
    files[`mcp/${framework}/${mcp.file}`] = mcpTemplates(framework, mcp, src);
    const routes = llmsRoutes(framework, null, '/docs', '/llms.mdx/docs');
    for (const [route, content] of templates(framework, routes, false, src)) {
      files[`${base}/${route.file}`] = content;
    }
    if (tanstack) {
      files[`${base}/lib/shared.ts`] =
        `import { createGetUrl } from 'fumadocs-core/source';\n\nexport const docsRoute = '/docs';\n${tanstackMarkdownUrl(false)}\n`;
      continue;
    }
    files[`${base}/lib/shared.ts`] =
      `import { createGetUrl } from 'fumadocs-core/source';\n\nexport const docsContentRoute = '/llms.mdx/docs';\n${markdownUrl(false)}\n`;
    if (framework === 'react-router') {
      files[`${base}/routes.ts`] = codemod(
        'routes.ts',
        `import { index, route, type RouteConfig } from '@react-router/dev/routes';

export default [
  index('routes/home.tsx'),
] satisfies RouteConfig;
`,
        (file) =>
          addReactRouterRoute(
            file,
            Object.values(routes).map((route) => ({ path: route.path, entry: route.file })),
          ),
      );
    }
    if (framework === 'next') {
      files[`${base}/next.config.ts`] = codemod(
        'next.config.ts',
        `import type { NextConfig } from 'next';

const config: NextConfig = {
  reactStrictMode: true,
};

export default config;
`,
        (file) => addNextRewrites(file, [markdownRewrite('/docs', routes.markdown, false)]),
      );
    }
  }
  return files;
}

/** `<feature tab="Next.js" title="app/llms.txt/route.ts">llms/next/app/llms.txt/route.ts</feature>` embeds a file generated by Fumadocs CLI */
export function remarkFeature() {
  const files = featureFiles();

  return defineMdastPlugin({
    name: 'remark-feature',
    mdxJsxFlowElement(node, ctx) {
      if (node.name !== 'feature') return;
      const key = ctx.textContent(node).trim();
      const value = files[key];
      if (value === undefined) throw new Error(`unknown feature file: ${key}`);

      const meta: string[] = [];
      for (const attr of node.attributes) {
        if (attr.type === 'mdxJsxAttribute' && typeof attr.value === 'string')
          meta.push(`${attr.name}="${attr.value}"`);
      }
      const code: Code = {
        type: 'code',
        lang: path.extname(key).slice(1),
        meta: meta.join(' '),
        value,
      };
      const start = node.position?.start.offset;
      const end = node.position?.end.offset;
      if (start !== undefined && end !== undefined) {
        (ctx.data._sourceEdits ??= []).push({
          start,
          end,
          text: `\`\`\`${code.lang} ${code.meta}\n${value}\n\`\`\``,
        });
      }
      return code;
    },
  });
}
