import type { ElementType, ReactElement } from 'react';

/**
 * Browser stub: Markdown rendering is server-only, components generated by the
 * `jsx` option of `remarkLLMs` render `null` in the browser.
 */
export function asMarkdown(): boolean {
  return false;
}

export function jsxComponents(
  components: Record<string, ElementType> | undefined,
): Record<string, ElementType> {
  return components ?? {};
}

export async function renderToMarkdown(): Promise<string> {
  throw new Error('`renderToMarkdown` is only available on the server.');
}

export async function renderRoute(_element: ReactElement): Promise<string | undefined> {
  throw new Error('`renderRoute` is only available on the server.');
}

export const md = () => {
  throw new Error('`md` is only available on the server.');
};
