name: Bug Report
description: Create a bug report
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue:

        - do a search of existing issues.
        - upgrade to the latest versions of Fumadocs.

        If you need help with your own project, you can start a discussion in the [Q&A Section](https://github.com/fuma-nama/fumadocs/discussions/categories/q-a).
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, or a link to the reproducible repository.
      placeholder: |
        1. Start the dev server (e.g. `npm run dev`)
        2. Click X
        3. Y will happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: A clear and concise description of what the bug is, and what you expected to happen.
      placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Framework
      description: Which React framework are you using?
      options:
        - Next.js
        - Tanstack Start
        - React Router
        - Waku
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Provide environment information
      description: |
        Include your framework, runtime, and relevant package versions.
        For Next.js projects, you can also run `next info` and paste the results.
      render: bash
      placeholder: |
        Framework: Next.js 16
        Operating System:
          Platform: darwin
          Arch: arm64
        Binaries:
          Node: 22.0.0
          npm: 10.0.0
        Relevant Packages:
          fumadocs-core: 16.0.0
          fumadocs-ui: 16.0.0
          fumadocs-mdx: 14.0.0
          react: 19.2.0
          react-dom: 19.2.0
          typescript: 5.9.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'Not sure'
        - 'Core'
        - 'UI'
        - 'CLI (create-fumadocs-app)'
        - 'Content Sources (e.g. Fumadocs MDX, Content Collections)'
        - 'Integrations (e.g OpenAPI, Typescript DocsGen)'
        - 'TypeScript (built-in types)'
        - 'Examples'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate.
      placeholder: |
        I tested my reproduction against different canary releases, and the first one that introduced the bug was "11.0.0", since reverting to "10.0.0" works.
