/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LangDocsSplatRouteImport } from './routes/$lang/docs/$'

const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/$lang/docs/$',
  path: '/$lang/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/search': typeof ApiSearchRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesByTo {
  '/api/search': typeof ApiSearchRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/search' | '/$lang' | '/$lang/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/search' | '/$lang' | '/$lang/docs/$'
  id: '__root__' | '/api/search' | '/$lang/' | '/$lang/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiSearchRoute: typeof ApiSearchRoute
  LangIndexRoute: typeof LangIndexRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/$lang/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiSearchRoute: ApiSearchRoute,
  LangIndexRoute: LangIndexRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
