'use client';

import * as Base from '@/components/codeblock';

/**
 * You are NOT supposed to use this component directly.
 *
 * This should be referenced in the output generated by the Rehype Code plugin.
 *
 * @internal
 */
export function Pre(props: Base.CodeBlockProps): React.ReactElement {
  return (
    <Base.CodeBlock {...props}>
      <Base.Pre>{props.children}</Base.Pre>
    </Base.CodeBlock>
  );
}
