import fs from 'node:fs/promises';
import { rehypeCode, type RehypeCodeOptions } from 'fumadocs-core/mdx-plugins/rehype-code';
import { rehypeToc } from 'fumadocs-core/mdx-plugins/rehype-toc';
import { remarkHeading } from 'fumadocs-core/mdx-plugins/remark-heading';
import { remarkStructure } from 'fumadocs-core/mdx-plugins/remark-structure';
import type { StructuredData } from 'fumadocs-core/mdx-plugins';
import type {
  DynamicSource,
  LoaderOutput,
  LoaderPlugin,
  MetaData,
  PageData,
  StaticSource,
  VirtualFile,
} from 'fumadocs-core/source';
import type { Root } from 'hast';
import remarkRehype from 'remark-rehype';
import { unified, type PluggableList } from 'unified';
import { VFile } from 'vfile';
import { buildPages, type BuiltPage } from './build';
import type { ModuleInterface } from './generated';
import { pythonPlugin } from './plugin';
import { createRenderer, type PythonRenderer } from './renderer';

export interface PythonConfig {
  /** path to the JSON file generated by `fumapy-generate` */
  file: string;
  /** additional remark plugins, applied before the structured data is collected */
  remarkPlugins?: PluggableList;
  /** additional rehype plugins, applied before the TOC is collected */
  rehypePlugins?: PluggableList;
  rehypeCodeOptions?: RehypeCodeOptions | false;
}

export type PythonPageKind = 'module' | 'class';

export interface PythonPage extends PageData {
  title: string;
  /** compile the page, at most once until the source is invalidated */
  load: () => Promise<PythonRenderer>;
  structuredData: () => Promise<StructuredData>;
  _python: { kind: PythonPageKind };
}

export interface PythonSource {
  staticSource: (options?: SourceOptions) => Promise<StaticSource<PythonSourceConfig>>;
  dynamicSource: (options?: SourceOptions) => DynamicSource<PythonSourceConfig>;
  /** decorates generated pages in the page tree with a `module`/`class` badge */
  loaderPlugin: () => LoaderPlugin;
}

export interface SourceOptions {
  /** base directory for virtual file paths */
  baseDir?: string;
}

type PythonSourceConfig = { pageData: PythonPage; metaData: MetaData };

/** Create a runtime Fumadocs content source from the JSON generated by `fumapy-generate`. */
export function createPython(config: PythonConfig): PythonSource {
  const processor = unified()
    .use(remarkHeading, { generateToc: false })
    .use(config.remarkPlugins ?? [])
    .use(remarkStructure)
    .use(remarkRehype, { passThrough: ['mdxJsxFlowElement', 'mdxJsxTextElement'] })
    .use(
      config.rehypeCodeOptions === false
        ? []
        : [[rehypeCode, { fallbackLanguage: 'plaintext', ...config.rehypeCodeOptions }]],
    )
    .use(config.rehypePlugins ?? [])
    .use(rehypeToc, { exportToc: { as: 'data' } });

  async function compile(
    page: BuiltPage,
    href: (target: BuiltPage) => string,
  ): Promise<PythonRenderer> {
    const file = new VFile({ path: page.path });
    const tree = (await processor.run(page.build(href), file)) as Root;

    return createRenderer({
      tree,
      structuredData: file.data.structuredData,
      rehypeToc: file.data.rehypeToc,
    });
  }

  function createSource({ baseDir }: SourceOptions = {}) {
    let loader: LoaderOutput | undefined;

    // links resolve through the loader the source is attached to, so pages
    // build lazily on compile rather than when files are listed
    function href(target: BuiltPage): string {
      const resolved = loader?.getPageByHref(`./${target.path}`, { dir: baseDir });
      if (!resolved) throw new Error(`cannot resolve the URL of ${target.path}`);

      return resolved.page.url;
    }

    async function files(): Promise<VirtualFile<PythonSourceConfig>[]> {
      const mod: ModuleInterface = JSON.parse(await fs.readFile(config.file, 'utf-8'));

      return buildPages(mod).map((page) => {
        let loaded: Promise<PythonRenderer> | undefined;
        const load = () => (loaded ??= compile(page, href));

        return {
          type: 'page',
          path: page.path,
          data: {
            title: page.title,
            load,
            structuredData: async () => (await load()).structuredData,
            _python: { kind: page.kind },
          },
        };
      });
    }

    return {
      baseDir,
      files,
      configureStatic(options: { loader: LoaderOutput }) {
        loader = options.loader;
      },
    };
  }

  return {
    dynamicSource: (options) => createSource(options),
    async staticSource(options) {
      const { files, ...source } = createSource(options);
      return { ...source, files: await files() };
    },
    loaderPlugin: pythonPlugin,
  };
}
