import type { Nodes } from 'mdast';
import type { VFile } from 'vfile';

/**
 * The Markdown of a node. A string covers the edits inside the node made before it and blocks those made after, a
 * function runs when stringifying instead, and its `s.stringify()` & `s.inner()` apply the edits inside.
 */
export type Replacement = string | ((s: Stringifier) => string);

interface Range {
  start: number;
  end: number;
}

/** created with every field, so edits share one object shape */
interface Edit {
  start: number;
  end: number;
  text: Replacement;
  node: Nodes | undefined;
  /** the range of the node that a range edit goes with */
  owner: Range | undefined;
}

/** an embedded source, output in place of the `host` range */
interface Embed extends Range {
  host: Range;
}

interface DocumentState {
  /** sources embedded after the document's, e.g. included files */
  embedded: string;
  embeds: Embed[];
  /** the ranges of embedded nodes, after the document's source */
  ranges: WeakMap<Nodes, Range>;
  replacements: { node: Nodes; text: Replacement; namespace: string | undefined }[];
}

const documents = new WeakMap<VFile, DocumentState>();

function getDocument(file: VFile): DocumentState {
  let doc = documents.get(file);
  if (!doc)
    documents.set(
      file,
      (doc = { embedded: '', embeds: [], ranges: new WeakMap(), replacements: [] }),
    );
  return doc;
}

function getRange(node: Nodes): Range | undefined {
  const start = node.position?.start.offset;
  const end = node.position?.end.offset;
  if (start !== undefined && end !== undefined) return { start, end };
}

/**
 * Replace the Markdown of an authored node, ignored without a position. The last edit of a node wins.
 *
 * @param namespace - limit the edit to the stringifiers of a namespace, like `search` for search records
 */
export function replaceSource(
  file: VFile,
  node: Nodes,
  text: Replacement,
  namespace?: 'search' | (string & {}),
): void {
  getDocument(file).replacements.push({ node, text, namespace });
}

/**
 * Replace an authored node with `content`, its children parsed from another source (e.g. included files). Their
 * positions are kept, stringifiers place `source` after the document's own.
 */
export function embedSource(file: VFile, node: Nodes, source: string, content: Nodes[]): void {
  const doc = getDocument(file);
  const base = String(file).length + doc.embedded.length + 1;
  doc.embedded += `\n${source}`;
  const host = doc.ranges.get(node) ?? getRange(node);
  if (host) doc.embeds.push({ start: base, end: base + source.length, host });

  // the content as embedded, plugins may replace its nodes later
  let start: number | undefined;
  let end = 0;
  const visit = (nodes: Nodes[]) => {
    for (const child of nodes) {
      const range = getRange(child);
      if (range) {
        range.start += base;
        range.end += base;
        doc.ranges.set(child, range);
        start ??= range.start;
        end = Math.max(end, range.end);
      }
      if ('children' in child) visit(child.children);
    }
  };
  visit(content);
  replaceSource(file, node, start === undefined ? '' : (s) => s.slice(start!, end));
}

/**
 * Markdown output backed by the authored source. Nodes without a position (e.g. generated by plugins) only appear
 * through replacements.
 */
export interface Stringifier {
  /** the document's source, followed by embedded sources */
  readonly source: string;
  /** the range of a node in `source` */
  range: (node: Nodes) => Range | undefined;
  /** replace a node in this output, after the edits of plugins */
  replace: (node: Nodes, text: Replacement) => void;
  /** replace a range of `source` in this output, an empty range inserts text, the edit goes with `node` if given */
  edit: (start: number, end: number, text: string, node?: Nodes) => void;
  /** a range of `source` as Markdown */
  slice: (start: number, end: number) => string;
  /** a node as Markdown, empty without a position */
  stringify: (node: Nodes) => string;
  /** the children of a node as Markdown, empty without positions */
  inner: (node: Nodes) => string;
  /** whether `range` is output inside `outer`, embedded sources are output in place of the node they replace */
  within: (range: Range, outer: Range) => boolean;
}

/**
 * @param namespace - also apply the edits of this namespace, like `search` for search records
 */
export function createStringifier(file: VFile, namespace?: 'search' | (string & {})): Stringifier {
  const doc = documents.get(file);
  const ranges = doc?.ranges;
  const embeds = doc?.embeds ?? [];
  const source = String(file) + (doc?.embedded ?? '');
  // the edits of plugins first, so the stringifier's own win
  const replaced = new Map<Nodes, Replacement>();
  for (const edit of doc?.replacements ?? [])
    if (edit.namespace === undefined || edit.namespace === namespace)
      replaced.set(edit.node, edit.text);
  const own: Edit[] = [];
  // nodes whose replacement is running, it doesn't apply inside itself
  const active = new Set<Nodes>();
  let edits: Edit[] | undefined;

  function getEdits(): Edit[] {
    if (edits) return edits;
    edits = own.slice();
    for (const [node, text] of replaced) {
      const range = s.range(node);
      if (range && range.end > range.start)
        edits.push({ start: range.start, end: range.end, text, node, owner: undefined });
    }

    // an outer edit comes first
    return edits.sort((a, b) => a.start - b.start || b.end - a.end);
  }

  /** the index of the first edit starting at or after `offset` */
  function search(list: Edit[], offset: number): number {
    let lo = 0;
    let hi = list.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (list[mid].start < offset) lo = mid + 1;
      else hi = mid;
    }
    return lo;
  }

  function render(start: number, end: number): string {
    const list = getEdits();
    let out = '';
    let cursor = start;
    // the last applied replacement, covering the edits inside it
    let appliedStart = start;
    let appliedEnd = start;
    for (let i = search(list, start); i < list.length; i++) {
      const edit = list[i];
      if (edit.start > end) break;
      if (edit.start < appliedEnd || edit.end > end) continue;
      if (edit.node && active.has(edit.node)) continue;

      const owner = edit.owner;
      // only with its whole node, when it isn't replaced
      if (
        owner &&
        (owner.start < start ||
          owner.end > end ||
          (owner.start >= appliedStart && owner.end <= appliedEnd))
      )
        continue;

      let text = edit.text;
      if (typeof text !== 'string') {
        active.add(edit.node!);
        text = text(s);
        active.delete(edit.node!);
      }

      out += source.slice(cursor, edit.start);
      if (edit.start === edit.end) {
        out += text;
      } else {
        out += indent(source, edit.start, text);
        appliedStart = edit.start;
        appliedEnd = edit.end;
      }
      cursor = edit.end;
    }

    return out + source.slice(cursor, end);
  }

  const s: Stringifier = {
    source,
    range: (node) => ranges?.get(node) ?? getRange(node),
    replace(node, text) {
      replaced.set(node, text);
      edits = undefined;
    },
    edit(start, end, text, node) {
      own.push({ start, end, text, node: undefined, owner: node && s.range(node) });
      edits = undefined;
    },
    slice(start, end) {
      return dedent(source, start, render(start, end));
    },
    stringify(node) {
      const range = s.range(node);
      return range ? s.slice(range.start, range.end) : '';
    },
    inner(node) {
      const range = s.range(node);
      if (!range || !('children' in node)) return '';
      const first = edge(node.children, false);
      const last = edge(node.children, true);
      let start = (first && lift(first, range)?.start) ?? range.end;
      let end = (last && lift(last, range)?.end) ?? range.start;
      // children replaced by plugins are in it through their edits
      const list = getEdits();
      for (let i = search(list, range.start + 1); i < list.length; i++) {
        const edit = list[i];
        if (edit.start >= range.end) break;
        if (edit.end > range.end) continue;
        start = Math.min(start, edit.start);
        end = Math.max(end, edit.end);
      }
      return end > start ? s.slice(start, end) : '';
    },
    within: (range, outer) => lift(range, outer) !== undefined,
  };

  /** `range` as output inside `outer`, embedded sources are output in place of the node they replace */
  function lift(range: Range, outer: Range): Range | undefined {
    while (range.start < outer.start || range.end > outer.end) {
      const embed = embeds.find((item) => range.start >= item.start && range.end <= item.end);
      if (!embed) return;
      range = embed.host;
    }
    return range;
  }

  /** the first or last node with a position, looking into the children of nodes without one */
  function edge(nodes: Nodes[], last: boolean): Range | undefined {
    for (let i = 0; i < nodes.length; i++) {
      const node = nodes[last ? nodes.length - 1 - i : i];
      const range = s.range(node) ?? ('children' in node ? edge(node.children, last) : undefined);
      if (range) return range;
    }
  }

  return s;
}

const containerPrefixRegex = /^(?:[ \t]*(?:>|[-*+](?=[ \t])|\d{1,9}[.)](?=[ \t])))*[ \t]*/;

/** the prefix of the containers (e.g. lists & blockquotes) at `start`, on the lines after the first */
function containerPrefix(source: string, start: number): string {
  const line = source.slice(source.lastIndexOf('\n', start - 1) + 1, start);
  return containerPrefixRegex.exec(line)![0].replace(/[^\t>]/g, ' ');
}

/** Markdown placed at `start`, continuing its containers, blank lines only carry their markers (e.g. `>`) */
function indent(source: string, start: number, text: string): string {
  if (!text.includes('\n')) return text;
  const prefix = containerPrefix(source, start);
  if (!prefix) return text;
  return text.replace(/\n(?=(.?))/g, (_, next: string) => `\n${next ? prefix : prefix.trimEnd()}`);
}

/** Markdown sliced from `start`, without the prefixes of its containers */
function dedent(source: string, start: number, text: string): string {
  if (!text.includes('\n')) return text;
  const prefix = containerPrefix(source, start);
  if (!prefix) return text;
  // the prefix only has whitespace & `>`
  return text.replace(new RegExp(`\\n(?:${prefix}|${prefix.trimEnd()}(?=\\r?\\n|$))`, 'g'), '\n');
}
